services:
  mysql:
    container_name: admin_menu_movies_db
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=adm_movies
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
    networks:
      - adm_movies_network

networks:
  adm_movies_network: